Book A Motorcycle - Frontend
GhausAliKhan/book-a-motorcycle-front-end pull request #7
Opened 2024-02-01 13:48 UTC by GhausAliKhan

### Overview:
This pull request focuses on the frontend development of the motorcycle booking system, leveraging React to create responsive components and styles for each specified feature.

### General Requirements:
- Ensure that the `codebase is free of linter errors`. Address and resolve any reported issues to maintain code quality.
- Confirm that the `Gitflow` has been followed correctly. This includes creating feature branches, keeping commits focused and meaningful, and following the defined branching strategy.
- Document work in a professional manner. Include clear and concise explanations of new features, changes, and any considerations for future development in `README.md`
- Adhere to the established best practices for `HTML` and `CSS`. This includes maintaining clean, semantic HTML structure and utilizing CSS efficiently for styling.
- Follow the defined best practices for `JavaScript`. Ensure code readability, use meaningful variable/function names, and adhere to the established coding standards.

### Components:
- Authentication Component:
  `Login.jsx`, `Logout.jsx` and `Signup.jsx`

- Navigation Panel Components:
  `Navbar.jsx` 
  `navComponents/Title.jsx`, `navComponents/Main.jsx` and `navComponents/Footer.jsx`

- Main Page Display Component:
  `Motorcycles.jsx`, `Motorcycle.jsx`, `Main.jsx` and `mainComponents/LeftButton.jsx`, `mainComponents/RightButton.jsx`

- Motorcycle Details Page Component:
  `MotorcycleDetails.jsx`

- Reservation Components:
  `Reserve.jsx`, `ReserveForm.jsx`

- My Reservations Component:
  `Reservations.jsx`

- Admin Components:
  `DeleteItem.jsx`, `DeleteMotorcycles.jsx`, `MotorcycleForm.jsx` and `Modal.jsx`

- Other Components: 
  `NotFound.jsx` and `Message.jsx`

### Redux
- `store.js`
- `motorcycleSlice.js`
- `reserveSlice.js`
- `userSlice.js`

### JavaScript
- `urls.js`
- `timeCalc.js`
- `reserveDisplay.js`

### Stylesheets:
- `login.css`
- `navbar.css`
- `reserve.css`
- `deleteMotorcycle.css`
- `mainSection.css`
- `motorcycle.css`
- `notfound.css`

### Reviewers:
Your careful review and feedback on the frontend implementation are highly appreciated.

2024-02-01 15:48 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!










#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2024-02-01 15:48 UTC, Meltrust commented on src/components/Reservations.jsx
> +const Reservations = () => {
- [x] When I go to "my reservations" as a new user, this happens:

![image](https://github.com/GhausAliKhan/book-a-motorcycle-front-end/assets/57421823/9d9bb2a5-3c57-48d3-8cbe-f2d4f23b16ed)

This might be because there are no items in the database yet.

Kindly, make sure the link works even if the user is brand new. 👍

2024-02-01 15:48 UTC, Meltrust commented on README.md
> +```
- [x] When I run this command I get this:

![image](https://github.com/GhausAliKhan/book-a-motorcycle-front-end/assets/57421823/231e3ca0-2b27-4755-9744-ceee4829940f)

This is because you have not included frontend tests.

Kindly, either include frontend tests or remove these instructions. 👍

2024-02-01 17:07 UTC, GhausAliKhan commented on src/components/Reservations.jsx
> +const Reservations = () => {
Hi @Meltrust,
I appreciate the review and I followed the steps you mentioned in your comment. But had no errors. You can also see here in this [video](https://www.loom.com/share/97f4b82ec40f431dbf3947de7a102239?sid=2a5cc1cc-1308-46b4-bb45-685851b5a94d)

2024-02-01 17:13 UTC, GhausAliKhan commented on src/components/Reservations.jsx
> +const Reservations = () => {
@Meltrust Looking forward to your reply!

2024-02-01 17:36 UTC, vichuge commented on src/components/Reservations.jsx
> +const Reservations = () => {
Hello everybody, I installed the application locally and everything looks good with this issue. So, I'll consider this as done. 😄

2024-02-01 17:42 UTC, GhausAliKhan commented on src/components/Reservations.jsx
> +const Reservations = () => {
Hey @vichuge,
Appreciate! 💯

2024-02-01 17:42 UTC, vichuge reviewed
Hi dear student, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![star_wars_almost_there](https://user-images.githubusercontent.com/20563252/121369354-644f4900-c901-11eb-9844-50c85d0f206b.gif)

## Suggested changes
_Check the comments under the review._

### Just consider to add tests in the project, even if you delete the ´npm run test´ instruction in the read me file, to have tests in the application is part of the requirements 😄 

<img width="570" alt="image" src="https://github.com/GhausAliKhan/book-a-motorcycle-front-end/assets/20563252/17a4d466-8450-48db-89bd-8a5eaf484ed9">

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2024-02-01 18:03 UTC, GhausAliKhan commented
### Hi @vichuge, 

As per the last reviewer, when he said "either include frontend tests or remove these instructions". This is because I updated the instructions in readme.
![image](https://github.com/GhausAliKhan/book-a-motorcycle-front-end/assets/94997336/add08479-88aa-4156-a449-7555624f2b8d)
![image](https://github.com/GhausAliKhan/book-a-motorcycle-front-end/assets/94997336/4640dcb3-eb2b-49f3-9cb3-9de7704b6e8d)

Also,
Regrettably, we were unable to include frontend tests in this pull request due to the unavailability of a team member. We acknowledge the importance of test coverage but time constraints compelled us to prioritize other critical features. Your understanding is appreciated. and assure you that we are committed to rectifying this in future updates.

2024-02-01 22:12 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  All tests but 1 are passing✔️




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2024-02-01 22:12 UTC, Meltrust commented on src/test/time.test.js
> +  test('should return valid==true for date >= today ', () => {
- [ ] This test is failing (don't worry, I got the solution):

![image](https://github.com/GhausAliKhan/book-a-motorcycle-front-end/assets/57421823/d70e7680-c2e2-43f4-9f0f-724d3674219b)

## Explanation

Let's put some console.logs to see how it behaves:

![image](https://github.com/GhausAliKhan/book-a-motorcycle-front-end/assets/57421823/afec28b7-799a-432b-82f3-ed88bd95b62d)


Result:

![image](https://github.com/GhausAliKhan/book-a-motorcycle-front-end/assets/57421823/794b3c43-b138-41a2-a09e-c81a426b2da2)

As you can see, for some reason the month in `today.getMonth()` is `1` probably due to a date incompatibility.

If you add `1` to the month `1` then the resulting number is `2`, which generates 1-2-2024.  

1-2-2024 is NOT bigger than today's date (1-2-2024), so the test returns false, and fails.

## Solution

Just add a day instead of adding a month.  So instead of doing `1 + today.getMonth()`, do `1 + today.getDate()` and the test will pass:

![image](https://github.com/GhausAliKhan/book-a-motorcycle-front-end/assets/57421823/38839108-8a33-48b2-8e70-ad520865aca1)

![image](https://github.com/GhausAliKhan/book-a-motorcycle-front-end/assets/57421823/46cff8b0-0b01-402b-a93e-fa5bf8010014)

Therefore for line 41:

```javascript
    const bookingDate = `${1 + today.getDate()}-${today.getMonth()}-${today.getFullYear()}`;
```

Now that you have the solution, please make this test pass and your project will be perfect. 💪

2024-02-02 04:29 UTC, GhausAliKhan commented on src/test/time.test.js
> +  test('should return valid==true for date >= today ', () => {
@Meltrust,
Thankyou for the suggested change 💯

2024-02-02 11:04 UTC, merged